// figma-export/Finance tracker app/src/app/components/Transactions.tsx
import React, { useState } from 'react';
import { useFinance, Transaction, Category } from '../context/FinanceContext';
import { Search, Plus, Trash2, Filter, Calendar } from 'lucide-react';
import { toast } from 'sonner';

const categories: Category[] = ['Food', 'Transport', 'Housing', 'Utilities', 'Entertainment', 'Health', 'Shopping', 'Income', 'Other'];

const Transactions: React.FC = () => {
  const { transactions, addTransaction, deleteTransaction } = useFinance();
  const [filter, setFilter] = useState<Category | 'All'>('All');
  const [searchTerm, setSearchTerm] = useState('');
  const [isAdding, setIsAdding] = useState(false);

  // New Transaction State
  const [newAmount, setNewAmount] = useState('');
  const [newDescription, setNewDescription] = useState('');
  const [newCategory, setNewCategory] = useState<Category>('Food');
  const [newType, setNewType] = useState<'income' | 'expense'>('expense');

  const filteredTransactions = transactions.filter(t => {
    const matchesFilter = filter === 'All' || t.category === filter;
    const matchesSearch = t.description.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  const handleAddTransaction = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newAmount || !newDescription) {
      toast.error("Please fill all fields");
      return;
    }

    addTransaction({
      amount: parseFloat(newAmount),
      description: newDescription,
      category: newCategory,
      type: newType,
      date: new Date().toISOString(),
    });

    setNewAmount('');
    setNewDescription('');
    setIsAdding(false);
    toast.success("Transaction added successfully");
  };

  return (
    <div className="bg-gray-50 min-h-screen">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl md:text-3xl font-bold text-gray-900">Transactions</h1>
        <button
          onClick={() => setIsAdding(!isAdding)}
          className="bg-blue-600 hover:bg-blue-700 text-white px-3 py-2 md:px-4 md:py-2 rounded-lg flex items-center gap-2 transition-colors text-sm md:text-base"
        >
          <Plus size={18} />
          <span className="hidden md:inline">Add Transaction</span>
          <span className="md:hidden">Add</span>
        </button>
      </div>

      {isAdding && (
        <div className="mb-6 bg-white p-4 md:p-6 rounded-2xl shadow-sm border border-gray-100 animate-in fade-in slide-in-from-top-4">
          <h3 className="text-lg md:text-xl font-bold mb-4">Add New Transaction</h3>
          <form onSubmit={handleAddTransaction} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <input
              type="text"
              placeholder="Description"
              value={newDescription}
              onChange={(e) => setNewDescription(e.target.value)}
              className="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none w-full"
            />
            <input
              type="number"
              placeholder="Amount"
              value={newAmount}
              onChange={(e) => setNewAmount(e.target.value)}
              className="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none w-full"
            />
            <select
              value={newCategory}
              onChange={(e) => setNewCategory(e.target.value as Category)}
              className="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none bg-white w-full"
            >
              {categories.map(c => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
            <div className="flex gap-2">
              <select
                value={newType}
                onChange={(e) => setNewType(e.target.value as 'income' | 'expense')}
                className="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none bg-white flex-1"
              >
                <option value="income">Income</option>
                <option value="expense">Expense</option>
              </select>
              <button
                type="submit"
                className="bg-green-600 hover:bg-green-700 text-white px-6 py-2 rounded-lg transition-colors font-medium"
              >
                Save
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="p-4 border-b border-gray-100 flex flex-col md:flex-row gap-4 justify-between items-center">
          <div className="relative w-full md:w-96">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
            <input
              type="text"
              placeholder="Search transactions..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
            />
          </div>
          <div className="flex items-center gap-2 w-full md:w-auto overflow-x-auto">
            <Filter size={20} className="text-gray-400" />
            <select
              value={filter}
              onChange={(e) => setFilter(e.target.value as Category | 'All')}
              className="border-none bg-transparent focus:ring-0 text-sm font-medium text-gray-600 cursor-pointer"
            >
              <option value="All">All Categories</option>
              {categories.map(c => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left py-4 px-6 text-sm font-semibold text-gray-600">Date</th>
                <th className="text-left py-4 px-6 text-sm font-semibold text-gray-600">Description</th>
                <th className="text-left py-4 px-6 text-sm font-semibold text-gray-600">Category</th>
                <th className="text-right py-4 px-6 text-sm font-semibold text-gray-600">Amount</th>
                <th className="text-right py-4 px-6 text-sm font-semibold text-gray-600">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredTransactions.map((transaction) => (
                <tr key={transaction.id} className="border-b border-gray-50 hover:bg-gray-50 transition-colors">
                  <td className="py-4 px-6 text-sm text-gray-600">
                    <div className="flex items-center gap-2">
                      <Calendar size={16} className="text-gray-400" />
                      {new Date(transaction.date).toLocaleDateString()}
                    </div>
                  </td>
                  <td className="py-4 px-6 text-sm font-medium text-gray-900">{transaction.description}</td>
                  <td className="py-4 px-6">
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                      transaction.type === 'income' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                    }`}>
                      {transaction.category}
                    </span>
                  </td>
                  <td className={`py-4 px-6 text-sm font-semibold text-right ${
                    transaction.type === 'income' ? 'text-green-600' : 'text-gray-900'
                  }`}>
                    {transaction.type === 'income' ? '+' : '-'}${transaction.amount.toFixed(2)}
                  </td>
                  <td className="py-4 px-6 text-right">
                    <button
                      onClick={() => deleteTransaction(transaction.id)}
                      className="text-gray-400 hover:text-red-600 transition-colors p-2 hover:bg-red-50 rounded-full"
                    >
                      <Trash2 size={18} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden">
          {filteredTransactions.map((transaction) => (
            <div key={transaction.id} className="p-4 border-b border-gray-100 last:border-none flex items-center justify-between">
              <div className="flex flex-col gap-1">
                <span className="font-medium text-gray-900">{transaction.description}</span>
                <div className="flex items-center gap-2 text-xs text-gray-500">
                  <span className={`px-2 py-0.5 rounded-full ${
                    transaction.type === 'income' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                  }`}>
                    {transaction.category}
                  </span>
                  <span>{new Date(transaction.date).toLocaleDateString()}</span>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <span className={`font-semibold ${
                  transaction.type === 'income' ? 'text-green-600' : 'text-gray-900'
                }`}>
                  {transaction.type === 'income' ? '+' : '-'}${transaction.amount.toFixed(2)}
                </span>
                <button
                  onClick={() => deleteTransaction(transaction.id)}
                  className="text-gray-400 hover:text-red-600 p-1"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            </div>
          ))}
        </div>

        {filteredTransactions.length === 0 && (
          <div className="text-center py-12 text-gray-500">
            No transactions found matching your criteria.
          </div>
        )}
      </div>
    </div>
  );
};

export default Transactions;

// app/pages/transactions.vue
<script setup lang="ts">
import { Search, Plus, Trash2, Filter, Calendar } from 'lucide-vue-next'
import { useCategories } from '~/domains/category/composables/useCategories'
import { useTransactions } from '~/domains/transaction/composables/useTransactions'
import { useCreateTransaction } from '~/domains/transaction/composables/useCreateTransaction'
import { useDeleteTransaction } from '~/domains/transaction/composables/useDeleteTransaction'
import { formatCurrency, formatDate } from '~/shared/utils/format'

definePageMeta({ layout: 'default' })

// --- Data ---
const { data: categories } = useCategories()

const searchTerm = ref('')
const filterCategory = ref('All')
const page = ref(1)
const limit = ref(20)
const categoryId = computed(() => filterCategory.value !== 'All' ? filterCategory.value : undefined)

const { data: txData, isLoading } = useTransactions({ page, limit, categoryId: categoryId as Ref<string | undefined> })

const filteredTransactions = computed(() => {
  if (!txData.value) return []
  if (!searchTerm.value) return txData.value.data
  const term = searchTerm.value.toLowerCase()
  return txData.value.data.filter(t => t.description.toLowerCase().includes(term))
})

const totalPages = computed(() => txData.value ? Math.ceil(txData.value.total / limit.value) : 1)

const categoryMap = computed(() =>
  Object.fromEntries((categories.value ?? []).map(c => [c.id, c]))
)

// --- Add Transaction ---
const isAdding = ref(false)
const form = reactive({
  description: '',
  amount: '',
  categoryId: '',
  type: 'expense' as 'income' | 'expense',
  date: new Date().toISOString().slice(0, 10),
})

const addMutation = useCreateTransaction()

function handleAdd(e: Event) {
  e.preventDefault()
  if (!form.amount || !form.description) return
  addMutation.mutate({
    amount: Math.round(parseFloat(form.amount) * 100),
    type: form.type,
    categoryId: form.categoryId || (categories.value?.[0]?.id ?? ''),
    description: form.description,
    date: form.date,
  }, {
    onSuccess: () => {
      form.description = ''
      form.amount = ''
      form.categoryId = categories.value?.[0]?.id ?? ''
      form.type = 'expense'
      form.date = new Date().toISOString().slice(0, 10)
      isAdding.value = false
    },
  })
}

// --- Delete Transaction ---
const deleteMutation = useDeleteTransaction()

// Init default category
watch(categories, (cats) => {
  const first = cats?.[0]
  if (first && !form.categoryId) form.categoryId = first.id
}, { immediate: true })

const fmtDate = formatDate
const fmtAmount = formatCurrency
</script>

<template>
  <div class="min-h-screen">
    <!-- Header -->
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-2xl md:text-3xl font-bold text-gray-900">Transactions</h1>
      <button
        class="bg-blue-600 hover:bg-blue-700 text-white px-3 py-2 md:px-4 md:py-2 rounded-lg flex items-center gap-2 transition-colors text-sm md:text-base"
        @click="isAdding = !isAdding"
      >
        <Plus :size="18" />
        <span class="hidden md:inline">Add Transaction</span>
        <span class="md:hidden">Add</span>
      </button>
    </div>

    <!-- Add Form -->
    <div
      v-if="isAdding"
      class="mb-6 bg-white p-4 md:p-6 rounded-2xl shadow-sm border border-gray-100"
    >
      <h3 class="text-lg md:text-xl font-bold mb-4">Add New Transaction</h3>
      <form class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4" @submit="handleAdd">
        <input
          v-model="form.description"
          type="text"
          placeholder="Description"
          class="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none lg:col-span-2"
        >
        <input
          v-model="form.amount"
          type="number"
          step="0.01"
          placeholder="Amount"
          class="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
        >
        <select
          v-model="form.categoryId"
          class="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none bg-white"
        >
          <option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option>
        </select>
        <div class="flex gap-2">
          <select
            v-model="form.type"
            class="p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none bg-white flex-1"
          >
            <option value="expense">Expense</option>
            <option value="income">Income</option>
          </select>
          <button
            type="submit"
            :disabled="addMutation.isPending.value"
            class="bg-green-600 hover:bg-green-700 disabled:opacity-50 text-white px-5 py-2 rounded-lg transition-colors font-medium"
          >
            Save
          </button>
        </div>
      </form>
    </div>

    <!-- Table Card -->
    <div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
      <!-- Toolbar -->
      <div class="p-4 border-b border-gray-100 flex flex-col md:flex-row gap-4 justify-between items-center">
        <div class="relative w-full md:w-96">
          <Search class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" :size="20" />
          <input
            v-model="searchTerm"
            type="text"
            placeholder="Search transactions..."
            class="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
          >
        </div>
        <div class="flex items-center gap-2 w-full md:w-auto">
          <Filter :size="20" class="text-gray-400 shrink-0" />
          <select
            v-model="filterCategory"
            class="border-none bg-transparent text-sm font-medium text-gray-600 cursor-pointer focus:outline-none"
          >
            <option value="All">All Categories</option>
            <option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option>
          </select>
        </div>
      </div>

      <!-- Loading -->
      <div v-if="isLoading" class="text-center py-12 text-gray-400">Loading...</div>

      <template v-else>
        <!-- Desktop Table -->
        <div class="hidden md:block overflow-x-auto">
          <table class="w-full">
            <thead class="bg-gray-50 border-b border-gray-100">
              <tr>
                <th class="text-left py-4 px-6 text-sm font-semibold text-gray-600">Date</th>
                <th class="text-left py-4 px-6 text-sm font-semibold text-gray-600">Description</th>
                <th class="text-left py-4 px-6 text-sm font-semibold text-gray-600">Category</th>
                <th class="text-right py-4 px-6 text-sm font-semibold text-gray-600">Amount</th>
                <th class="text-right py-4 px-6 text-sm font-semibold text-gray-600">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="tx in filteredTransactions"
                :key="tx.id"
                class="border-b border-gray-50 hover:bg-gray-50 transition-colors"
              >
                <td class="py-4 px-6 text-sm text-gray-600">
                  <div class="flex items-center gap-2">
                    <Calendar :size="16" class="text-gray-400" />
                    {{ fmtDate(tx.date) }}
                  </div>
                </td>
                <td class="py-4 px-6 text-sm font-medium text-gray-900">{{ tx.description }}</td>
                <td class="py-4 px-6">
                  <span
                    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
                    :class="tx.type === 'income' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'"
                  >
                    {{ categoryMap[tx.categoryId]?.name ?? tx.categoryId }}
                  </span>
                </td>
                <td
                  class="py-4 px-6 text-sm font-semibold text-right"
                  :class="tx.type === 'income' ? 'text-green-600' : 'text-gray-900'"
                >
                  {{ tx.type === 'income' ? '+' : '-' }}{{ fmtAmount(tx.amount) }}
                </td>
                <td class="py-4 px-6 text-right">
                  <button
                    class="text-gray-400 hover:text-red-600 transition-colors p-2 hover:bg-red-50 rounded-full"
                    @click="deleteMutation.mutate(tx.id)"
                  >
                    <Trash2 :size="18" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Mobile Cards -->
        <div class="md:hidden">
          <div
            v-for="tx in filteredTransactions"
            :key="tx.id"
            class="p-4 border-b border-gray-100 last:border-none flex items-center justify-between"
          >
            <div class="flex flex-col gap-1">
              <span class="font-medium text-gray-900">{{ tx.description }}</span>
              <div class="flex items-center gap-2 text-xs text-gray-500">
                <span
                  class="px-2 py-0.5 rounded-full"
                  :class="tx.type === 'income' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'"
                >
                  {{ categoryMap[tx.categoryId]?.name ?? tx.categoryId }}
                </span>
                <span>{{ fmtDate(tx.date) }}</span>
              </div>
            </div>
            <div class="flex items-center gap-3">
              <span
                class="font-semibold"
                :class="tx.type === 'income' ? 'text-green-600' : 'text-gray-900'"
              >
                {{ tx.type === 'income' ? '+' : '-' }}{{ fmtAmount(tx.amount) }}
              </span>
              <button
                class="text-gray-400 hover:text-red-600 p-1"
                @click="deleteMutation.mutate(tx.id)"
              >
                <Trash2 :size="16" />
              </button>
            </div>
          </div>
        </div>

        <!-- Empty state -->
        <div v-if="filteredTransactions.length === 0" class="text-center py-12 text-gray-500">
          No transactions found matching your criteria.
        </div>

        <!-- Pagination -->
        <div v-if="totalPages > 1" class="flex items-center justify-center gap-4 p-4 border-t border-gray-100">
          <button
            :disabled="page <= 1"
            class="px-4 py-2 text-sm border border-gray-200 rounded-lg disabled:opacity-40 hover:bg-gray-50 transition-colors"
            @click="page--"
          >
            Previous
          </button>
          <span class="text-sm text-gray-600">Page {{ page }} of {{ totalPages }}</span>
          <button
            :disabled="page >= totalPages"
            class="px-4 py-2 text-sm border border-gray-200 rounded-lg disabled:opacity-40 hover:bg-gray-50 transition-colors"
            @click="page++"
          >
            Next
          </button>
        </div>
      </template>
    </div>
  </div>
</template>
